### ISSUE TITLE
Slow startup times

### ISSUE THREAD

**Issue by stratosgear** [jjuliano/sensible.emacs.d#2]
Hi,

I was trying your emacs configuration (beginner emacser here) and the startup time is like more than 30 secs long (not just the first startup, but everytime I start emacs).

Most of the time is spent with message like:

```
Unicode fotns - Mapping unicode fonts in fontselect-default  [some rolling% here]
``` 

followed with multiple flyspell message ending at the bottom with an error message like:

```
Error enabling Flyspell mode
(Error: No word lists can be found for the language "en_GB"
```

Any ideas?

**Comment by stratosgear** [comment]
I found this: https://github.com/rolandwalker/unicode-fonts#startup-speed

But is persistent-soft.el, installed?

**Comment by jjuliano** [comment]
Hello @stratosgear,

Thanks for pointing that out. I didn't knew that. I have added `persistent-soft.el` to the default packages.

~ Joel
